services:
  backend-unit-tests:
    build: ./backend
    command: ["uv", "run", "pytest", "tests", "-s"]

  backend:
    build: ./backend
    environment:
      - SERVE_STATIC_FILES=true
    volumes:
      - frontend_dist:/app/static
    command: ["fastapi", "run", "--host", "0.0.0.0", "src/nba_wins_pool/main_backend.py"]
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://backend:8000/favicon.ico"]
      interval: 5s
      timeout: 2s
      retries: 5
    depends_on:
      - frontend-builder

  frontend-builder:
    build: ./frontend
    environment:
      - VITE_BACKEND_URL=
    command: ["npm", "run", "build"]
    volumes:
      - frontend_dist:/app/dist

  playwright:
    build: ./playwright_tests
    environment:
      - BASE_URL=http://backend:8000/
    ports:
      - "9323:9323"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  frontend_dist:
