services:
  backend:
    build: ./backend
    volumes:
      - appdata:/app/data
    environment:
      - SERVE_DETAILED_ERRORS=true

  frontend:
    build: ./frontend
    command: ["npm", "run", "build"]

volumes:
  appdata:
