# development environment defaults
services:
  backend:
    ports:
    - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
    command: ["fastapi", "dev", "--host", "0.0.0.0", "src/nba_wins_pool/main_backend.py"]  
  
  frontend:
    ports:
    - "5173:5173"
    - "8080:5173"
    build: ./frontend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./package.json
    command: ["npm", "run", "dev"]
