services:
  backend-unit-tests:
    build: ./backend
    command: ["uv", "run", "pytest", "tests", "-s"]
  backend:
    build: ./backend
    environment:
      - SERVE_STATIC_FILES=true
    volumes:
      - frontend_dist:/app/static
    command: ["fastapi", "run", "--host", "0.0.0.0", "src/nba_wins_pool/main_backend.py"]
    # environment:
    #   - CORS_ALLOW_ALL=true
    # # runs on port 8000 by default
    # command: ["fastapi", "run", "--host", "0.0.0.0", "src/nba_wins_pool/main_backend.py"]
    healthcheck:
      test: ["CMD", "wget", "--spider", "backend:8000/docs/"]
      interval: 5s
      timeout: 2s
      retries: 5
  frontend:
    build: ./frontend
    environment:
      - VITE_BACKEND_URL=
      # - VITE_BACKEND_URL=http://backend:8000
    # runs on port 4173 by default
    command: ["npm", "run", "build"]
    volumes:
      - frontend_dist:/app/dist
    # healthcheck:
    #   test: ["CMD", "wget", "--spider", "frontend:4173/"]
    #   interval: 5s
    #   timeout: 2s
    #   retries: 5
  playwright:
    build: ./playwright_tests
    environment:
      - BASE_URL=http://backend:8000/
      # - FRONTEND_BASE_URL=http://frontend:4173/
    ports:
      - "9323:9323"
    depends_on:
      # frontend:
      #   condition: service_healthy
      backend:
        condition: service_healthy

volumes:
  frontend_dist: