# production environment, run with -f compose.yml -f compose.prod.yml
services:
  web:
    restart: unless-stopped
    ports:
    - "8080:8000"
    command: ["fastapi", "run", "--host", "0.0.0.0", "src/nba_wins_pool/main_backend.py"]