services:
  backend:
    build: ./backend
    depends_on:
      - frontend
    volumes:
      - appdata:/app/data

  frontend:
    build: ./frontend
    command: ["npm", "run", "build"]

volumes:
  appdata:
