services:
  backend-format:
    build: ./backend
    volumes:
      - ./backend:/app/src
      - ./backend/tests:/app/tests
    command: >
      sh -c "uv run ruff check . --fix && uv run ruff format ."

  frontend-format:
    build: ./frontend
    command: ["npm", "run", "format"]
    volumes:
      - ./frontend:/app/src

  discord-format:
    build: ./discord
    volumes:
      - ./discord:/discord_app
    command: >
      sh -c "uv run ruff check . --fix && uv run ruff format ."
