# production environment, run with -f compose.yml -f compose.prod.yml
services:
  backend:
    restart: unless-stopped
    ports:
    - "43565:8000"
    environment:
      - SERVE_STATIC_FILES=true
    volumes:
      - frontend_dist:/app/static
    command: ["fastapi", "run", "--host", "0.0.0.0", "backend/src/nba_wins_pool/main_backend.py"]

  frontend:
    environment:
      # use relative path
      - VITE_BACKEND_URL=
    volumes:
      - frontend_dist:/app/dist

volumes:
  frontend_dist:
