services:
  backend:
    build:
      dockerfile: ./backend/Dockerfile
      context: .
    depends_on:
      - frontend
    volumes:
      - appdata:/app/data

  frontend:
    build: ./frontend
    command: ["npm", "run", "build"]

volumes:
  appdata:
