[project]
name = "nba-wins-pool"
version = "0.0.1"
description = "Web app for displaying standings and analysis for NBA Wins Pool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.4",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
dev = [
    "pre-commit>=4.0.1",
    "ruff>=0.7.3",
    "fastapi-cli>=0.0.5",
]

[tool.ruff]
line-length = 120
