[project]
name = "discord"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "discord-py>=2.6.4",
    "pandas>=2.0.3",
    "requests>=2.32.4",
    "table2ascii>=1.1.3",
]
