"""add_nba_vegas_data

Revision ID: 033945df4143
Revises: f9f5f3359c5f
Create Date: 2025-11-21 22:06:37.421046

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "033945df4143"
down_revision: Union[str, Sequence[str], None] = "f9f5f3359c5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nba_vegas_data",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("reg_season_wins", sa.Numeric(scale=2), nullable=False),
        sa.Column("team_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("over_wins_odds", sa.Integer(), nullable=True),
        sa.Column("under_wins_odds", sa.Integer(), nullable=True),
        sa.Column("make_playoffs_odds", sa.Integer(), nullable=True),
        sa.Column("miss_playoffs_odds", sa.Integer(), nullable=True),
        sa.Column("win_conference_odds", sa.Integer(), nullable=True),
        sa.Column("win_finals_odds", sa.Integer(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season", "team_id", "fetched_at", name="uq_vegas_data_season_team_fetched"),
    )
    op.create_index(op.f("ix_nba_vegas_data_fetched_at"), "nba_vegas_data", ["fetched_at"], unique=False)
    op.create_index(op.f("ix_nba_vegas_data_season"), "nba_vegas_data", ["season"], unique=False)
    op.create_index(op.f("ix_nba_vegas_data_team_id"), "nba_vegas_data", ["team_id"], unique=False)
    op.alter_column("auctioneventlog", "payload", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    op.drop_constraint(op.f("uq_external_data_key"), "external_data", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_external_data_key"), "external_data", ["key"], postgresql_nulls_not_distinct=False
    )
    op.alter_column("auctioneventlog", "payload", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    op.drop_index(op.f("ix_nba_vegas_data_team_id"), table_name="nba_vegas_data")
    op.drop_index(op.f("ix_nba_vegas_data_season"), table_name="nba_vegas_data")
    op.drop_index(op.f("ix_nba_vegas_data_fetched_at"), table_name="nba_vegas_data")
    op.drop_table("nba_vegas_data")
    # ### end Alembic commands ###
