"""initialize

Revision ID: 11588b6a4367
Revises:
Create Date: 2025-09-02 01:41:04.953600

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "11588b6a4367"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_member_name"), "member", ["name"], unique=False)
    op.create_table(
        "pool",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("rules", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pool_slug"), "pool", ["slug"], unique=True)
    op.create_table(
        "team",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("logo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column("nba_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_team_nba_id"), "team", ["nba_id"], unique=True)
    op.create_index(op.f("ix_team_slug"), "team", ["slug"], unique=True)
    op.create_table(
        "teamownership",
        sa.Column("pool_id", sa.Uuid(), nullable=False),
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team_slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("auction_price", sa.Numeric(scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["member.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pool_id"],
            ["pool.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_slug"],
            ["team.slug"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teamownership_owner_id"), "teamownership", ["owner_id"], unique=False)
    op.create_index(op.f("ix_teamownership_pool_id"), "teamownership", ["pool_id"], unique=False)
    op.create_index(op.f("ix_teamownership_season"), "teamownership", ["season"], unique=False)
    op.create_index(op.f("ix_teamownership_team_slug"), "teamownership", ["team_slug"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_teamownership_team_slug"), table_name="teamownership")
    op.drop_index(op.f("ix_teamownership_season"), table_name="teamownership")
    op.drop_index(op.f("ix_teamownership_pool_id"), table_name="teamownership")
    op.drop_index(op.f("ix_teamownership_owner_id"), table_name="teamownership")
    op.drop_table("teamownership")
    op.drop_index(op.f("ix_team_slug"), table_name="team")
    op.drop_index(op.f("ix_team_nba_id"), table_name="team")
    op.drop_table("team")
    op.drop_index(op.f("ix_pool_slug"), table_name="pool")
    op.drop_table("pool")
    op.drop_index(op.f("ix_member_name"), table_name="member")
    op.drop_table("member")
    # ### end Alembic commands ###
