"""add division to team

Revision ID: 14ebf197c4b6
Revises: df6a47162ffe
Create Date: 2026-03-31 04:23:44.896380

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14ebf197c4b6"
down_revision: Union[str, Sequence[str], None] = "df6a47162ffe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_external_data_key"), "external_data", type_="unique")
    op.add_column("team", sa.Column("division", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team", "division")
    op.create_unique_constraint(
        op.f("uq_external_data_key"), "external_data", ["key"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
