"""add team_season_result and pool_team_season_result tables

Revision ID: 891a6785eedb
Revises: 36a3fcedf954
Create Date: 2026-09-24 02:20:02.281060

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "891a6785eedb"
down_revision: Union[str, Sequence[str], None] = "36a3fcedf954"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teamseasonresult",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("actual_wins", sa.Integer(), nullable=False),
        sa.Column("actual_losses", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teamseasonresult_season"), "teamseasonresult", ["season"], unique=False)
    op.create_index(op.f("ix_teamseasonresult_team_id"), "teamseasonresult", ["team_id"], unique=False)
    op.create_table(
        "poolteamseasonresult",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pool_id", sa.Uuid(), nullable=False),
        sa.Column("pool_season_id", sa.Uuid(), nullable=False),
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("roster_id", sa.Uuid(), nullable=False),
        sa.Column("roster_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("projected_wins", sa.Float(), nullable=True),
        sa.Column("projected_price", sa.Numeric(scale=2), nullable=True),
        sa.Column("auction_price", sa.Numeric(scale=2), nullable=True),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["pool_id"], ["pool.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pool_season_id"], ["poolseason.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["roster_id"], ["roster.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_poolteamseasonresult_pool_id"), "poolteamseasonresult", ["pool_id"], unique=False)
    op.create_index(
        op.f("ix_poolteamseasonresult_pool_season_id"), "poolteamseasonresult", ["pool_season_id"], unique=False
    )
    op.create_index(op.f("ix_poolteamseasonresult_roster_id"), "poolteamseasonresult", ["roster_id"], unique=False)
    op.create_index(op.f("ix_poolteamseasonresult_season"), "poolteamseasonresult", ["season"], unique=False)
    op.create_index(op.f("ix_poolteamseasonresult_team_id"), "poolteamseasonresult", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_poolteamseasonresult_team_id"), table_name="poolteamseasonresult")
    op.drop_index(op.f("ix_poolteamseasonresult_season"), table_name="poolteamseasonresult")
    op.drop_index(op.f("ix_poolteamseasonresult_roster_id"), table_name="poolteamseasonresult")
    op.drop_index(op.f("ix_poolteamseasonresult_pool_season_id"), table_name="poolteamseasonresult")
    op.drop_index(op.f("ix_poolteamseasonresult_pool_id"), table_name="poolteamseasonresult")
    op.drop_table("poolteamseasonresult")
    op.drop_index(op.f("ix_teamseasonresult_team_id"), table_name="teamseasonresult")
    op.drop_index(op.f("ix_teamseasonresult_season"), table_name="teamseasonresult")
    op.drop_table("teamseasonresult")
    # ### end Alembic commands ###
