"""add_simulation_results

Revision ID: 9d02d7cb56c8
Revises: 1a4a33f7ac40
Create Date: 2026-04-16 04:39:52.636519

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d02d7cb56c8"
down_revision: Union[str, Sequence[str], None] = "1a4a33f7ac40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulation_team_result",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phase", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("n_sims", sa.Integer(), nullable=False),
        sa.Column("simulated_at", sa.DateTime(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("power_rating", sa.Float(), nullable=False),
        sa.Column("mean_rs_wins", sa.Float(), nullable=False),
        sa.Column("mean_po_wins", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season", "team_id", "simulated_at"),
    )
    op.create_index(op.f("ix_simulation_team_result_season"), "simulation_team_result", ["season"], unique=False)
    op.create_index(
        op.f("ix_simulation_team_result_simulated_at"), "simulation_team_result", ["simulated_at"], unique=False
    )
    op.create_index(op.f("ix_simulation_team_result_team_id"), "simulation_team_result", ["team_id"], unique=False)
    op.create_table(
        "simulation_roster_result",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phase", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("n_sims", sa.Integer(), nullable=False),
        sa.Column("simulated_at", sa.DateTime(), nullable=False),
        sa.Column("roster_id", sa.Uuid(), nullable=False),
        sa.Column("pool_id", sa.Uuid(), nullable=False),
        sa.Column("mean_rs_wins", sa.Float(), nullable=False),
        sa.Column("mean_po_wins", sa.Float(), nullable=False),
        sa.Column("win_pct", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pool_id"],
            ["pool.id"],
        ),
        sa.ForeignKeyConstraint(
            ["roster_id"],
            ["roster.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season", "roster_id", "simulated_at"),
    )
    op.create_index(op.f("ix_simulation_roster_result_pool_id"), "simulation_roster_result", ["pool_id"], unique=False)
    op.create_index(
        op.f("ix_simulation_roster_result_roster_id"), "simulation_roster_result", ["roster_id"], unique=False
    )
    op.create_index(op.f("ix_simulation_roster_result_season"), "simulation_roster_result", ["season"], unique=False)
    op.create_index(
        op.f("ix_simulation_roster_result_simulated_at"), "simulation_roster_result", ["simulated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_simulation_roster_result_simulated_at"), table_name="simulation_roster_result")
    op.drop_index(op.f("ix_simulation_roster_result_season"), table_name="simulation_roster_result")
    op.drop_index(op.f("ix_simulation_roster_result_roster_id"), table_name="simulation_roster_result")
    op.drop_index(op.f("ix_simulation_roster_result_pool_id"), table_name="simulation_roster_result")
    op.drop_table("simulation_roster_result")
    op.drop_index(op.f("ix_simulation_team_result_team_id"), table_name="simulation_team_result")
    op.drop_index(op.f("ix_simulation_team_result_simulated_at"), table_name="simulation_team_result")
    op.drop_index(op.f("ix_simulation_team_result_season"), table_name="simulation_team_result")
    op.drop_table("simulation_team_result")
    # ### end Alembic commands ###
