"""add_playoff_data

Revision ID: 1a4a33f7ac40
Revises: 14ebf197c4b6
Create Date: 2026-04-13 04:21:23.616025

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a4a33f7ac40"
down_revision: Union[str, Sequence[str], None] = "14ebf197c4b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nba_projections", sa.Column("bpi", sa.Float(), nullable=True))
    op.add_column("nba_projections", sa.Column("playoff_bpi", sa.Float(), nullable=True))
    op.add_column("nba_projections", sa.Column("reach_conf_semis_prob", sa.Float(), nullable=True))
    op.add_column("nba_projections", sa.Column("reach_conf_finals_prob", sa.Float(), nullable=True))
    op.add_column("nba_projections", sa.Column("reach_conf_semis_odds", sa.Integer(), nullable=True))
    op.add_column("nba_projections", sa.Column("reach_conf_finals_odds", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nba_projections", "reach_conf_finals_odds")
    op.drop_column("nba_projections", "reach_conf_semis_odds")
    op.drop_column("nba_projections", "reach_conf_finals_prob")
    op.drop_column("nba_projections", "reach_conf_semis_prob")
    op.drop_column("nba_projections", "playoff_bpi")
    op.drop_column("nba_projections", "bpi")
    # ### end Alembic commands ###
