"""add_nba_projections_data

Revision ID: 7bf04b1e95c9
Revises: f9f5f3359c5f
Create Date: 2026-01-10 21:52:24.284776

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bf04b1e95c9"
down_revision: Union[str, Sequence[str], None] = "f9f5f3359c5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nba_projections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("season", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("projection_date", sa.Date(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("team_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("reg_season_wins", sa.Float(), nullable=True),
        sa.Column("over_wins_prob", sa.Float(), nullable=True),
        sa.Column("make_playoffs_prob", sa.Float(), nullable=True),
        sa.Column("win_conference_prob", sa.Float(), nullable=True),
        sa.Column("win_finals_prob", sa.Float(), nullable=True),
        sa.Column("over_wins_odds", sa.Integer(), nullable=True),
        sa.Column("under_wins_odds", sa.Integer(), nullable=True),
        sa.Column("make_playoffs_odds", sa.Integer(), nullable=True),
        sa.Column("miss_playoffs_odds", sa.Integer(), nullable=True),
        sa.Column("win_conference_odds", sa.Integer(), nullable=True),
        sa.Column("win_finals_odds", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "season", "team_id", "projection_date", "source", name="uq_projections_data_season_team_date_source"
        ),
    )
    op.create_index(op.f("ix_nba_projections_fetched_at"), "nba_projections", ["fetched_at"], unique=False)
    op.create_index(op.f("ix_nba_projections_projection_date"), "nba_projections", ["projection_date"], unique=False)
    op.create_index(op.f("ix_nba_projections_season"), "nba_projections", ["season"], unique=False)
    op.create_index(op.f("ix_nba_projections_source"), "nba_projections", ["source"], unique=False)
    op.create_index(op.f("ix_nba_projections_team_id"), "nba_projections", ["team_id"], unique=False)
    op.alter_column("auctioneventlog", "payload", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    op.drop_constraint(op.f("uq_external_data_key"), "external_data", type_="unique")
    op.add_column("team", sa.Column("conference", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team", "conference")
    op.create_unique_constraint(
        op.f("uq_external_data_key"), "external_data", ["key"], postgresql_nulls_not_distinct=False
    )
    op.alter_column("auctioneventlog", "payload", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    op.drop_index(op.f("ix_nba_projections_team_id"), table_name="nba_projections")
    op.drop_index(op.f("ix_nba_projections_source"), table_name="nba_projections")
    op.drop_index(op.f("ix_nba_projections_season"), table_name="nba_projections")
    op.drop_index(op.f("ix_nba_projections_projection_date"), table_name="nba_projections")
    op.drop_index(op.f("ix_nba_projections_fetched_at"), table_name="nba_projections")
    op.drop_table("nba_projections")
    # ### end Alembic commands ###
