name: PR Checks
on:
  pull_request:

jobs:
  backned-unit-tests:
    runs-on: self-hosted
    env:
      BUILD_DIR: tmp/pr_builds/PR_${{ github.event.number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            path: ${{ env.BUILD_DIR }}

      - name: Backend tests
        working-directory: ${{ env.BUILD_DIR }}
        run: docker-compose -f compose.testing.yml run --build backend-unit-tests

      - name: Cleanup
        if: always()
        run: rm -rf ${{ env.BUILD_DIR }}
