name: PR Checks
on:
  pull_request:

jobs:
  tests:
    name: Containerized Tests
    runs-on: self-hosted
    env:
      BUILD_DIR: tmp/pr_builds/PR_${{ github.event.number }}/${{ github.run_id }}
      DOCKER_PROJECT_NAME: backend-unit-tests-${{ github.event.number }}-${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            path: ${{ env.BUILD_DIR }}

      - name: Backend Unit Tests with Docker
        working-directory: ${{ env.BUILD_DIR }}
        run: make backend_tests PROJECT_NAME=${{ env.DOCKER_PROJECT_NAME }}

      - name: Playwright E2E Tests with Docker
        working-directory: ${{ env.BUILD_DIR }}
        run: make e2e_tests PROJECT_NAME=${{ env.DOCKER_PROJECT_NAME }}

      - name: Cleanup Docker Resources - Docker Compose Down
        if: always()
        working-directory: ${{ env.BUILD_DIR }}
        run: docker compose -p ${{ env.DOCKER_PROJECT_NAME }} -f compose.testing.yml down --volumes

      - name: Cleanup Docker Resources - Images
        if: always()
        working-directory: ${{ env.BUILD_DIR }}
        run: docker images --filter "label=com.docker.compose.project=${{ env.DOCKER_PROJECT_NAME }}" -q | xargs -r docker rmi -f

      - name: Cleanup Files
        if: always()
        run: rm -rfv ${{ env.BUILD_DIR }}
